/**
 * Country flag emojis and utilities for dropdown display
 */

export const COUNTRY_FLAGS: Record<string, string> = {
  // Major powerlifting countries
  'USA': '🇺🇸',
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'CAN': '🇨🇦',
  'United Kingdom': '🇬🇧',
  'UK': '🇬🇧',
  'GBR': '🇬🇧',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Australia': '🇦🇺',
  'AUS': '🇦🇺',
  'Germany': '🇩🇪',
  'DEU': '🇩🇪',
  'France': '🇫🇷',
  'FRA': '🇫🇷',
  'Russia': '🇷🇺',
  'RUS': '🇷🇺',
  'Japan': '🇯🇵',
  'JPN': '🇯🇵',
  'Sweden': '🇸🇪',
  'SWE': '🇸🇪',
  'Norway': '🇳🇴',
  'NOR': '🇳🇴',
  'Finland': '🇫🇮',
  'FIN': '🇫🇮',
  'Denmark': '🇩🇰',
  'DEN': '🇩🇰',
  'Netherlands': '🇳🇱',
  'NLD': '🇳🇱',
  'Belgium': '🇧🇪',
  'BEL': '🇧🇪',
  'Switzerland': '🇨🇭',
  'SUI': '🇨🇭',
  'Austria': '🇦🇹',
  'AUT': '🇦🇹',
  'Italy': '🇮🇹',
  'ITA': '🇮🇹',
  'Spain': '🇪🇸',
  'ESP': '🇪🇸',
  'Portugal': '🇵🇹',
  'POR': '🇵🇹',
  'Poland': '🇵🇱',
  'POL': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'CZE': '🇨🇿',
  'Slovakia': '🇸🇰',
  'SVK': '🇸🇰',
  'Hungary': '🇭🇺',
  'HUN': '🇭🇺',
  'Romania': '🇷🇴',
  'ROU': '🇷🇴',
  'Bulgaria': '🇧🇬',
  'BUL': '🇧🇬',
  'Croatia': '🇭🇷',
  'CRO': '🇭🇷',
  'Slovenia': '🇸🇮',
  'SLO': '🇸🇮',
  'Serbia': '🇷🇸',
  'SRB': '🇷🇸',
  'Ukraine': '🇺🇦',
  'UKR': '🇺🇦',
  'Belarus': '🇧🇾',
  'BLR': '🇧🇾',
  'Lithuania': '🇱🇹',
  'LTU': '🇱🇹',
  'Latvia': '🇱🇻',
  'LAT': '🇱🇻',
  'Estonia': '🇪🇪',
  'EST': '🇪🇪',
  'Brazil': '🇧🇷',
  'BRA': '🇧🇷',
  'Argentina': '🇦🇷',
  'ARG': '🇦🇷',
  'Mexico': '🇲🇽',
  'MEX': '🇲🇽',
  'Chile': '🇨🇱',
  'CHI': '🇨🇱',
  'Colombia': '🇨🇴',
  'COL': '🇨🇴',
  'Venezuela': '🇻🇪',
  'VEN': '🇻🇪',
  'Peru': '🇵🇪',
  'PER': '🇵🇪',
  'Ecuador': '🇪🇨',
  'ECU': '🇪🇨',
  'Uruguay': '🇺🇾',
  'URU': '🇺🇾',
  'Paraguay': '🇵🇾',
  'PAR': '🇵🇾',
  'Bolivia': '🇧🇴',
  'BOL': '🇧🇴',
  'China': '🇨🇳',
  'CHN': '🇨🇳',
  'Taiwan': '🇹🇼',
  'TPE': '🇹🇼',
  'South Korea': '🇰🇷',
  'KOR': '🇰🇷',
  'India': '🇮🇳',
  'IND': '🇮🇳',
  'Thailand': '🇹🇭',
  'THA': '🇹🇭',
  'Singapore': '🇸🇬',
  'SIN': '🇸🇬',
  'Malaysia': '🇲🇾',
  'MAS': '🇲🇾',
  'Indonesia': '🇮🇩',
  'INA': '🇮🇩',
  'Philippines': '🇵🇭',
  'PHI': '🇵🇭',
  'Vietnam': '🇻🇳',
  'VIE': '🇻🇳',
  'Kazakhstan': '🇰🇿',
  'KAZ': '🇰🇿',
  'Iran': '🇮🇷',
  'IRI': '🇮🇷',
  'Israel': '🇮🇱',
  'ISR': '🇮🇱',
  'Turkey': '🇹🇷',
  'TUR': '🇹🇷',
  'South Africa': '🇿🇦',
  'RSA': '🇿🇦',
  'Egypt': '🇪🇬',
  'EGY': '🇪🇬',
  'Morocco': '🇲🇦',
  'MAR': '🇲🇦',
  'Algeria': '🇩🇿',
  'ALG': '🇩🇿',
  'Tunisia': '🇹🇳',
  'TUN': '🇹🇳',
  'Nigeria': '🇳🇬',
  'NGR': '🇳🇬',
  'Kenya': '🇰🇪',
  'KEN': '🇰🇪',
  'Ghana': '🇬🇭',
  'GHA': '🇬🇭',
  'New Zealand': '🇳🇿',
  'NZL': '🇳🇿',
  'Iceland': '🇮🇸',
  'ISL': '🇮🇸',
  'Ireland': '🇮🇪',
  'IRL': '🇮🇪',
  'Luxembourg': '🇱🇺',
  'LUX': '🇱🇺',
  'Mongolia': '🇲🇳',
  'MGL': '🇲🇳',
  'Uzbekistan': '🇺🇿',
  'UZB': '🇺🇿',
  'Georgia': '🇬🇪',
  'GEO': '🇬🇪',
  'Armenia': '🇦🇲',
  'ARM': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'AZE': '🇦🇿',
};

/**
 * Get flag emoji for a country name
 */
export function getCountryFlag(countryName: string): string {
  return COUNTRY_FLAGS[countryName] || '🏳️';
}

/**
 * Format country name with flag for dropdown display
 */
export function formatCountryOption(countryName: string): string {
  const flag = getCountryFlag(countryName);
  return `${flag} ${countryName}`;
}

/**
 * Get all countries with their flags for dropdown options
 */
export function getCountriesWithFlags(countries: string[]): { value: string; label: string }[] {
  return countries.map(country => ({
    value: country,
    label: country === 'All' ? 'All Countries' : formatCountryOption(country)
  }));
}